version: "3"
services:
  postgres:
    container_name: notpal_postgres
    image: postgres:14-alpine
    env_file:
      - ./backend/.env
    expose:
      - 5470
    volumes:
      # - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data/
    restart: unless-stopped
    command: -p 5470

  api:
    container_name: notpal_django
    build:
      context: ./backend
    ports:
      - "8017:8017"
    command: python manage.py runserver 8017
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
    pgdata:
